import { createContext, useContext, useEffect, useState } from "react";

const TRANSLATIONS = {
  tr: {
    // Sidebar
    dashboard: "Dashboard",
    products: "Ürün Kontrolü",
    production: "Üretim Girişi",
    customers: "Müşteriler",
    sales: "Depo Çıkış",
    stock: "Stok Durumu",
    reports: "Raporlar",
    settings: "Ayarlar",
    logout: "Çıkış Yap",

    // Common
    save: "Kaydet",
    cancel: "İptal",
    delete: "Sil",
    edit: "Düzenle",
    add: "Ekle",
    search: "Ara",
    filter: "Filtrele",
    export: "Dışa Aktar",
    excel: "Excel",
    csv: "CSV",
    confirm: "Onayla",
    yes: "Evet",
    no: "Hayır",
    active: "Aktif",
    inactive: "Pasif",
    loading: "Yükleniyor...",
    no_records: "Kayıt bulunamadı",
    clear: "Temizle",
    start_date: "Başlangıç",
    end_date: "Bitiş",
    actions: "İşlem",
    status: "Durum",
    notes: "Notlar",
    description: "Açıklama",
    date: "Tarih",
    name: "Ad",
    email: "E-posta",
    role: "Rol",
    quantity: "Miktar",
    weight: "Ağırlık",
    unit: "Birim",
    category: "Kategori",
    total: "Toplam",
    price: "Fiyat",
    sale_price: "Satış Fiyatı",

    // Page titles
    dashboard_subtitle: "Genel iş durumu özeti",
    products_subtitle: "Ürün tanımları ve stok yönetimi",
    production_subtitle: "Üretim kayıtları stoğa otomatik eklenir",
    customers_subtitle: "Müşteri bilgileri ve çıkış geçmişi",
    sales_subtitle: "Depo çıkış kaydı — stoktan otomatik düşülür",
    stock_subtitle: "Güncel stoklar ve hareket geçmişi",
    reports_subtitle: "Stok, üretim ve çıkış analizleri",
    settings_subtitle: "Şirket profili, kullanıcılar ve sistem yönetimi",

    // Dashboard
    total_products: "Toplam Ürün",
    total_stock_kg: "Toplam Stok (kg)",
    today_exit: "Bugünkü Çıkış",
    month_exit: "Bu Ay Çıkış",
    low_stock_title: "Minimum Stok Altındaki Ürünler",
    no_low_stock: "Düşük stoklu ürün yok",
    top_products: "En Çok Çıkan 5 Ürün",
    recent_productions: "Son Üretim Hareketleri",
    recent_exits: "Son Çıkış Hareketleri",
    category_value_title: "Stok Mali Değer Dağılımı (Kategori)",
    exit_trend: "Son 14 Gün Çıkış Trendi (kg)",
    no_exits: "Henüz çıkış kaydı yok",
    no_production: "Henüz üretim kaydı yok",

    // Products
    new_product: "Yeni Ürün",
    edit_product: "Ürün Düzenle",
    product_name: "Ürün Adı",
    product_code: "Ürün Kodu",
    unit_weight: "Birim Ağırlık (kg)",
    current_stock: "Güncel Stok",
    min_stock: "Min. Stok",
    stock: "Stok",
    code: "Kod",

    // Production
    new_production: "Üretim Kaydı",
    lot_no: "Lot / Parti No",

    // Customers
    new_customer: "Yeni Müşteri",
    edit_customer: "Müşteri Düzenle",
    customer_name: "Müşteri / Firma Adı",
    customer_type: "Tip",
    phone: "Telefon",
    address: "Adres",
    tax_no: "Vergi No",
    total_exits_value: "Toplam Çıkış",
    past_exits: "Geçmiş Çıkışlar",

    // Sales / Depo Çıkış
    new_exit: "Yeni Çıkış",
    exit_receipt: "Çıkış Fişi",
    select_customer: "Müşteri seçin",
    add_item: "Ürün Ekle",
    total_quantity: "Toplam Adet",
    total_weight: "Toplam Ağırlık",
    estimated_value: "Tahmini Mali Değer",

    // Stock
    movement_history: "Hareket Geçmişi",
    stock_status: "Stok Durumu",
    manual_adjust: "Manuel Düzeltme",
    total_in: "Toplam Giriş",
    total_out: "Toplam Çıkış",

    // Reports
    current_stock_report: "Güncel Stok",
    financial_report: "Mali Değer",
    distribution_report: "Ürün/Kategori",
    production_report: "Üretim",
    sales_report: "Çıkış",
    stock_weight: "Stok Ağırlığı (kg)",
    total_production: "Toplam Üretim",
    daily_avg: "Günlük Ortalama",
    weekly_avg: "Haftalık Ortalama",
    monthly_avg: "Aylık Ortalama",
    avg_production_per_product: "Ürün Bazlı Ortalama Üretim",
    top_customers: "Müşteri Bazlı Çıkış",
    top_products_by_weight: "En Çok Çıkan Ürünler (kg)",

    // Settings
    profile_info: "Profil Bilgileri",
    app_settings: "Uygulama Ayarları",
    user_management: "Kullanıcı Yönetimi",
    company_profile: "Şirket Profili",
    language: "Dil",
    theme: "Tema",
    currency: "Para Birimi",
    date_format: "Tarih Formatı",
    edit_profile: "Profili Düzenle",
    change_password: "Şifre Değiştir",
    current_password: "Mevcut Şifre",
    new_password: "Yeni Şifre",
    permission_count: "İzin Sayısı",
    permissions: "İzinler",
    all_permissions: "Tüm yetkiler",
    permission_dialog_desc: "Aşağıdan kullanıcının hangi modüllerde ne yapabileceğini seçin.",
    permission_save: "İzinleri Kaydet",
  },
  en: {
    dashboard: "Dashboard",
    products: "Product Control",
    production: "Production Entry",
    customers: "Customers",
    sales: "Warehouse Exit",
    stock: "Stock Status",
    reports: "Reports",
    settings: "Settings",
    logout: "Logout",

    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    filter: "Filter",
    export: "Export",
    excel: "Excel",
    csv: "CSV",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    active: "Active",
    inactive: "Inactive",
    loading: "Loading...",
    no_records: "No records found",
    clear: "Clear",
    start_date: "Start",
    end_date: "End",
    actions: "Actions",
    status: "Status",
    notes: "Notes",
    description: "Description",
    date: "Date",
    name: "Name",
    email: "Email",
    role: "Role",
    quantity: "Quantity",
    weight: "Weight",
    unit: "Unit",
    category: "Category",
    total: "Total",
    price: "Price",
    sale_price: "Sale Price",

    dashboard_subtitle: "Overall business overview",
    products_subtitle: "Product definitions & stock management",
    production_subtitle: "Production entries auto-update stock",
    customers_subtitle: "Customer info & exit history",
    sales_subtitle: "Warehouse exit log — auto deducts from stock",
    stock_subtitle: "Current stock & movement history",
    reports_subtitle: "Stock, production & exit analytics",
    settings_subtitle: "Company profile, users & system management",

    total_products: "Total Products",
    total_stock_kg: "Total Stock (kg)",
    today_exit: "Today's Exit",
    month_exit: "This Month Exit",
    low_stock_title: "Products Below Min Stock",
    no_low_stock: "No low-stock products",
    top_products: "Top 5 Exited Products",
    recent_productions: "Recent Production Activity",
    recent_exits: "Recent Exit Activity",
    category_value_title: "Stock Financial Value by Category",
    exit_trend: "Last 14 Days Exit Trend (kg)",
    no_exits: "No exits yet",
    no_production: "No production yet",

    new_product: "New Product",
    edit_product: "Edit Product",
    product_name: "Product Name",
    product_code: "Product Code",
    unit_weight: "Unit Weight (kg)",
    current_stock: "Current Stock",
    min_stock: "Min. Stock",
    stock: "Stock",
    code: "Code",

    new_production: "Production Record",
    lot_no: "Lot / Batch No",

    new_customer: "New Customer",
    edit_customer: "Edit Customer",
    customer_name: "Customer / Company Name",
    customer_type: "Type",
    phone: "Phone",
    address: "Address",
    tax_no: "Tax No",
    total_exits_value: "Total Exit",
    past_exits: "Past Exits",

    new_exit: "New Exit",
    exit_receipt: "Exit Receipt",
    select_customer: "Select customer",
    add_item: "Add Item",
    total_quantity: "Total Qty",
    total_weight: "Total Weight",
    estimated_value: "Estimated Value",

    movement_history: "Movement History",
    stock_status: "Stock Status",
    manual_adjust: "Manual Adjust",
    total_in: "Total In",
    total_out: "Total Out",

    current_stock_report: "Current Stock",
    financial_report: "Financial Value",
    distribution_report: "Product/Category",
    production_report: "Production",
    sales_report: "Exit",
    stock_weight: "Stock Weight (kg)",
    total_production: "Total Production",
    daily_avg: "Daily Average",
    weekly_avg: "Weekly Average",
    monthly_avg: "Monthly Average",
    avg_production_per_product: "Average Production per Product",
    top_customers: "Exit by Customer",
    top_products_by_weight: "Top Products (kg)",

    profile_info: "Profile Information",
    app_settings: "App Settings",
    user_management: "User Management",
    company_profile: "Company Profile",
    language: "Language",
    theme: "Theme",
    currency: "Currency",
    date_format: "Date Format",
    edit_profile: "Edit Profile",
    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    permission_count: "Permission Count",
    permissions: "Permissions",
    all_permissions: "All permissions",
    permission_dialog_desc: "Select which modules and actions this user can perform.",
    permission_save: "Save Permissions",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "tr");

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => {
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.tr;
    return dict[key] ?? TRANSLATIONS.tr[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
