import { createContext, useContext, useEffect, useState } from "react";

const TRANSLATIONS = {
  tr: {
    // ===== Sidebar =====
    dashboard: "Dashboard",
    products: "Ürün Kontrolü",
    production: "Üretim Girişi",
    customers: "Müşteriler",
    sales: "Depo Çıkış",
    stock: "Stok Durumu",
    reports: "Raporlar",
    settings: "Ayarlar",
    logout: "Çıkış Yap",

    // ===== Common =====
    save: "Kaydet",
    saving: "Kaydediliyor...",
    cancel: "İptal",
    delete: "Sil",
    edit: "Düzenle",
    add: "Ekle",
    search: "Ara",
    filter: "Filtrele",
    export: "Dışa Aktar",
    excel: "Excel",
    csv: "CSV",
    confirm: "Onayla",
    yes: "Evet",
    no: "Hayır",
    active: "Aktif",
    inactive: "Pasif",
    loading: "Yükleniyor...",
    no_records: "Kayıt bulunamadı",
    clear: "Temizle",
    start_date: "Başlangıç",
    end_date: "Bitiş",
    actions: "İşlem",
    status: "Durum",
    notes: "Notlar",
    description: "Açıklama",
    date: "Tarih",
    name: "Ad",
    email: "E-posta",
    role: "Rol",
    quantity: "Miktar",
    weight: "Ağırlık",
    unit: "Birim",
    category: "Kategori",
    total: "Toplam",
    price: "Fiyat",
    sale_price: "Satış Fiyatı",
    optional: "opsiyonel",
    all: "Tümü",
    no_data: "Veri yok",
    code: "Kod",

    // ===== Page subtitles =====
    dashboard_subtitle: "Genel iş durumu özeti",
    products_subtitle: "Ürün tanımları ve stok yönetimi",
    production_subtitle: "Üretim kayıtları stoğa otomatik eklenir",
    customers_subtitle: "Müşteri bilgileri ve çıkış geçmişi",
    sales_subtitle: "Depo çıkış kaydı — stoktan otomatik düşülür",
    stock_subtitle: "Güncel stoklar ve hareket geçmişi",
    reports_subtitle: "Stok, üretim ve çıkış analizleri",
    settings_subtitle: "Şirket profili, kullanıcılar ve sistem yönetimi",

    // ===== Dashboard =====
    total_products: "Toplam Ürün",
    total_stock_kg: "Toplam Stok (kg)",
    today_exit: "Bugünkü Çıkış",
    month_exit: "Bu Ay Çıkış",
    low_stock_title: "Minimum Stok Altındaki Ürünler",
    no_low_stock: "Düşük stoklu ürün yok",
    top_products: "En Çok Çıkan 5 Ürün",
    recent_productions: "Son Üretim Hareketleri",
    recent_exits: "Son Çıkış Hareketleri",
    category_weight_title: "Kategoriye Göre Toplam Stok (kg)",
    category_sale_value_title: "Kategoriye Göre Potansiyel Satış Değeri",
    exit_trend: "Son 14 Gün Çıkış Trendi (kg)",
    no_exits: "Henüz çıkış kaydı yok",
    no_production: "Henüz üretim kaydı yok",
    units_count: "ürün",
    weight_label: "Ağırlık",

    // ===== Products page =====
    new_product: "Yeni Ürün",
    edit_product: "Ürün Düzenle",
    product_name: "Ürün Adı",
    product_code: "Ürün Kodu",
    unit_weight: "Birim Ağırlık (kg)",
    current_stock: "Güncel Stok",
    min_stock: "Min. Stok",
    min_stock_level: "Min Stok Seviyesi",
    products_title: "Ürün Kontrolü",
    products_table_title_product: "Ürün",
    search_products_placeholder: "Ad veya kod ara...",
    all_categories: "Tüm Kategoriler",
    deactivate_product_q: "Ürünü pasif yapmak istediğinize emin misiniz?",
    deactivate_product_desc: "pasif duruma getirilecek. Stok kayıtları korunur.",
    toast_product_added: "Ürün eklendi",
    toast_product_updated: "Ürün güncellendi",
    toast_product_deactivated: "Ürün pasif yapıldı",
    toast_product_required: "Ürün adı ve kodu zorunludur",
    unit_adet: "Adet",
    unit_kg: "Kg",
    unit_koli: "Koli",

    // ===== Production page =====
    new_production: "Üretim Kaydı",
    new_production_record: "Yeni Üretim Kaydı",
    lot_no: "Lot / Parti No",
    lot_short: "Lot / Parti",
    production_table_amount: "Miktar",
    cost: "Maliyet",
    toast_production_added: "Üretim kaydedildi, stoğa eklendi",
    toast_production_deleted: "Üretim kaydı silindi, stoktan düşüldü",
    toast_select_product: "Ürün seçin",
    toast_valid_quantity: "Geçerli bir miktar girin",
    delete_production_q: "Üretim kaydı silinsin mi?",
    delete_production_desc: "Kayıt silindiğinde ürün stoğundan ilgili miktar düşülecek.",

    // ===== Customers page =====
    new_customer: "Yeni Müşteri",
    edit_customer: "Müşteri Düzenle",
    customer_name: "Müşteri / Firma Adı",
    customer_type: "Tip",
    phone: "Telefon",
    address: "Adres",
    tax_no: "Vergi No",
    total_exits_value: "Toplam Çıkış",
    past_exits: "Geçmiş Çıkışlar",
    customer_search_placeholder: "İsim, telefon veya e-posta...",
    all_types: "Tüm Tipler",
    name_or_company: "Ad / Firma",
    customers_no_record: "Kayıt yok",
    deactivate_customer_q: "Müşteri pasif yapılsın mı?",
    deactivate_customer_desc: "pasif duruma alınacak.",
    toast_customer_added: "Müşteri eklendi",
    toast_customer_updated: "Müşteri güncellendi",
    toast_customer_deactivated: "Müşteri pasif yapıldı",
    toast_customer_name_required: "Müşteri adı zorunlu",
    total_sales_amount: "Toplam Satış",
    past_sales: "Geçmiş Satışlar",
    no_sales: "Satış kaydı yok",
    payment: "Ödeme",
    amount: "Tutar",
    products_label: "Ürünler",

    // ===== Sales / Depo Çıkış =====
    new_exit: "Yeni Çıkış",
    exit_receipt: "Çıkış Fişi",
    select_customer: "Müşteri seçin",
    add_item: "Ürün Ekle",
    total_quantity: "Toplam Adet",
    total_weight: "Toplam Ağırlık",
    estimated_value: "Tahmini Mali Değer",

    // ===== Stock page =====
    movement_history: "Hareket Geçmişi",
    stock_status: "Stok Durumu",
    manual_adjust: "Manuel Düzeltme",
    manual_stock_adjust: "Manuel Stok Düzeltme",
    total_in: "Toplam Giriş",
    total_out: "Toplam Çıkış",
    sale_value: "Satış Değeri",
    stock_weight_kg: "Stok Ağırlığı (kg)",
    previous_stock: "Önceki Stok",
    new_stock: "Yeni Stok",
    in_qty: "Giriş",
    out_qty: "Çıkış",
    type_col: "Tip",
    movement_type: "Tip",
    product_filter: "Ürün Filtre",
    all_products: "Tüm Ürünler",
    no_movements: "Hareket yok",
    no_products: "Ürün yok",
    low_stock_label: "Düşük Stok",
    normal_label: "Normal",
    quantity_signed: "Miktar (+ giriş / - çıkış)",
    type_uretim: "Üretim",
    type_satis: "Satış",
    type_manuel: "Manuel Düzeltme",
    type_fire: "Fire",
    type_iade: "İade",
    type_baslangic: "Başlangıç",
    toast_stock_adjusted: "Stok düzeltme kaydedildi",
    toast_amount_zero: "Miktar 0 olamaz",

    // ===== Reports page =====
    current_stock_report: "Güncel Stok",
    financial_report: "Mali Değer",
    distribution_report: "Ürün/Kategori",
    production_report: "Üretim",
    sales_report: "Çıkış",
    stock_weight: "Stok Ağırlığı (kg)",
    total_production: "Toplam Üretim",
    daily_avg: "Günlük Ortalama",
    weekly_avg: "Haftalık Ortalama",
    monthly_avg: "Aylık Ortalama",
    avg_production_per_product: "Ürün Bazlı Ortalama Üretim",
    top_customers: "Müşteri Bazlı Çıkış",
    top_products_by_weight: "En Çok Çıkan Ürünler (kg)",
    total_stock_fin_value: "Toplam Stok Mali Değeri",
    potential_sale_value: "Potansiyel Satış Değeri",
    total_stock_count: "Toplam Stok Adedi",
    category_financial_value: "Kategori Bazlı Mali Değer",
    product_count: "Ürün Sayısı",
    stock_qty: "Stok (adet)",
    financial_value: "Mali Değer",
    category_stock_dist: "Kategoriye Göre Stok Dağılımı (kg)",
    product_stock_chart: "Ürün Stok Grafiği",
    daily_production_kg: "Günlük Üretim (kg)",
    total_quantity_unit: "Toplam (adet)",
    total_quantity_kg: "Toplam (kg)",
    records: "Kayıt",
    avg_qty: "Ortalama Adet",
    avg_kg: "Ortalama kg",
    total_exit_kg: "Toplam Çıkış (kg)",
    total_exit_qty: "Toplam Çıkış (adet)",
    exits_count: "Çıkış Adedi",
    daily_avg_kg: "Günlük Ort. (kg)",
    daily_exit_kg: "Günlük Çıkış (kg)",
    customer: "Müşteri",
    exit_qty: "Çıkış (adet)",
    exit_kg: "Çıkış (kg)",
    product_based_exit: "Ürün Bazlı Çıkış",
    product: "Ürün",
    stock_by_category_header: "Kategori Bazlı Toplam (kg)",

    // ===== Settings =====
    profile_info: "Profil Bilgileri",
    app_settings: "Uygulama Ayarları",
    user_management: "Kullanıcı Yönetimi",
    company_profile: "Şirket Profili",
    language: "Dil",
    theme: "Tema",
    currency: "Para Birimi",
    date_format: "Tarih Formatı",
    edit_profile: "Profili Düzenle",
    change_password: "Şifre Değiştir",
    current_password: "Mevcut Şifre",
    new_password: "Yeni Şifre",
    permission_count: "İzin Sayısı",
    permissions: "İzinler",
    all_permissions: "Tüm yetkiler",
    permission_dialog_desc: "Aşağıdan kullanıcının hangi modüllerde ne yapabileceğini seçin.",
    permission_save: "İzinleri Kaydet",
    settings_title: "Ayarlar",
    company_profile_pdf_note: "PDF fişler ve raporlar için kullanılır",
    logo: "Logo",
    upload: "Yükle",
    uploading: "Yükleniyor...",
    logo_size_note: "JPG, PNG, WEBP, GIF • Maks. 2 MB",
    company_name: "Şirket Adı",
    website: "Web Sitesi",
    save_company: "Şirket Bilgilerini Kaydet",
    toast_company_name_required: "Şirket adı zorunlu",
    toast_logo_too_big: "Logo en fazla 2 MB olabilir",
    toast_logo_type: "Sadece JPG, PNG, WEBP veya GIF",
    toast_logo_updated: "Logo güncellendi",
    toast_logo_removed: "Logo kaldırıldı",
    toast_company_updated: "Şirket bilgileri güncellendi",
    toast_updated: "Güncellendi",
    toast_perms_updated: "İzinler güncellendi",
    toast_user_deleted: "Kullanıcı silindi",
    toast_user_updated: "Kullanıcı güncellendi",
    toast_profile_updated: "Profil güncellendi",
    user_management_desc: "Her kullanıcının modül bazlı yetkilerini ayrı ayrı düzenleyebilirsiniz.",
    registered: "Kayıt",
    role_admin: "Yönetici",
    role_personel: "Personel",
    role_rapor: "Sadece Rapor",
    permission_unit: "izin",
    permission_management: "Yetki Yönetimi",
    select_all: "Tümünü Seç",
    deselect_all: "Tümünü Kaldır",
    delete_user_q: "Kullanıcı silinsin mi?",
    delete_user_desc: "silinecek.",
  },
  en: {
    dashboard: "Dashboard",
    products: "Product Control",
    production: "Production Entry",
    customers: "Customers",
    sales: "Warehouse Exit",
    stock: "Stock Status",
    reports: "Reports",
    settings: "Settings",
    logout: "Logout",

    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    filter: "Filter",
    export: "Export",
    excel: "Excel",
    csv: "CSV",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    active: "Active",
    inactive: "Inactive",
    loading: "Loading...",
    no_records: "No records found",
    clear: "Clear",
    start_date: "Start",
    end_date: "End",
    actions: "Actions",
    status: "Status",
    notes: "Notes",
    description: "Description",
    date: "Date",
    name: "Name",
    email: "Email",
    role: "Role",
    quantity: "Quantity",
    weight: "Weight",
    unit: "Unit",
    category: "Category",
    total: "Total",
    price: "Price",
    sale_price: "Sale Price",
    optional: "optional",
    all: "All",
    no_data: "No data",
    code: "Code",

    dashboard_subtitle: "Overall business overview",
    products_subtitle: "Product definitions & stock management",
    production_subtitle: "Production entries auto-update stock",
    customers_subtitle: "Customer info & exit history",
    sales_subtitle: "Warehouse exit log — auto deducts from stock",
    stock_subtitle: "Current stock & movement history",
    reports_subtitle: "Stock, production & exit analytics",
    settings_subtitle: "Company profile, users & system management",

    total_products: "Total Products",
    total_stock_kg: "Total Stock (kg)",
    today_exit: "Today's Exit",
    month_exit: "This Month Exit",
    low_stock_title: "Products Below Min Stock",
    no_low_stock: "No low-stock products",
    top_products: "Top 5 Exited Products",
    recent_productions: "Recent Production Activity",
    recent_exits: "Recent Exit Activity",
    category_weight_title: "Total Stock by Category (kg)",
    category_sale_value_title: "Potential Sale Value by Category",
    exit_trend: "Last 14 Days Exit Trend (kg)",
    no_exits: "No exits yet",
    no_production: "No production yet",
    units_count: "products",
    weight_label: "Weight",

    new_product: "New Product",
    edit_product: "Edit Product",
    product_name: "Product Name",
    product_code: "Product Code",
    unit_weight: "Unit Weight (kg)",
    current_stock: "Current Stock",
    min_stock: "Min. Stock",
    min_stock_level: "Min Stock Level",
    products_title: "Product Control",
    products_table_title_product: "Product",
    search_products_placeholder: "Search by name or code...",
    all_categories: "All Categories",
    deactivate_product_q: "Deactivate this product?",
    deactivate_product_desc: "will be deactivated. Stock records are preserved.",
    toast_product_added: "Product added",
    toast_product_updated: "Product updated",
    toast_product_deactivated: "Product deactivated",
    toast_product_required: "Product name and code are required",
    unit_adet: "pcs",
    unit_kg: "kg",
    unit_koli: "box",

    new_production: "Production Record",
    new_production_record: "New Production Record",
    lot_no: "Lot / Batch No",
    lot_short: "Lot / Batch",
    production_table_amount: "Quantity",
    cost: "Cost",
    toast_production_added: "Production saved, stock updated",
    toast_production_deleted: "Production deleted, stock adjusted",
    toast_select_product: "Select a product",
    toast_valid_quantity: "Enter a valid quantity",
    delete_production_q: "Delete production record?",
    delete_production_desc: "Deleting will deduct the corresponding amount from stock.",

    new_customer: "New Customer",
    edit_customer: "Edit Customer",
    customer_name: "Customer / Company Name",
    customer_type: "Type",
    phone: "Phone",
    address: "Address",
    tax_no: "Tax No",
    total_exits_value: "Total Exit",
    past_exits: "Past Exits",
    customer_search_placeholder: "Name, phone or email...",
    all_types: "All Types",
    name_or_company: "Name / Company",
    customers_no_record: "No records",
    deactivate_customer_q: "Deactivate customer?",
    deactivate_customer_desc: "will be deactivated.",
    toast_customer_added: "Customer added",
    toast_customer_updated: "Customer updated",
    toast_customer_deactivated: "Customer deactivated",
    toast_customer_name_required: "Customer name required",
    total_sales_amount: "Total Sales",
    past_sales: "Past Sales",
    no_sales: "No sales recorded",
    payment: "Payment",
    amount: "Amount",
    products_label: "Products",

    new_exit: "New Exit",
    exit_receipt: "Exit Receipt",
    select_customer: "Select customer",
    add_item: "Add Item",
    total_quantity: "Total Qty",
    total_weight: "Total Weight",
    estimated_value: "Estimated Value",

    movement_history: "Movement History",
    stock_status: "Stock Status",
    manual_adjust: "Manual Adjust",
    manual_stock_adjust: "Manual Stock Adjustment",
    total_in: "Total In",
    total_out: "Total Out",
    sale_value: "Sale Value",
    stock_weight_kg: "Stock Weight (kg)",
    previous_stock: "Previous Stock",
    new_stock: "New Stock",
    in_qty: "In",
    out_qty: "Out",
    type_col: "Type",
    movement_type: "Type",
    product_filter: "Product Filter",
    all_products: "All Products",
    no_movements: "No movements",
    no_products: "No products",
    low_stock_label: "Low Stock",
    normal_label: "Normal",
    quantity_signed: "Quantity (+ in / - out)",
    type_uretim: "Production",
    type_satis: "Sale",
    type_manuel: "Manual",
    type_fire: "Waste",
    type_iade: "Return",
    type_baslangic: "Initial",
    toast_stock_adjusted: "Stock adjustment saved",
    toast_amount_zero: "Amount cannot be 0",

    current_stock_report: "Current Stock",
    financial_report: "Financial Value",
    distribution_report: "Product/Category",
    production_report: "Production",
    sales_report: "Exit",
    stock_weight: "Stock Weight (kg)",
    total_production: "Total Production",
    daily_avg: "Daily Average",
    weekly_avg: "Weekly Average",
    monthly_avg: "Monthly Average",
    avg_production_per_product: "Average Production per Product",
    top_customers: "Exit by Customer",
    top_products_by_weight: "Top Products (kg)",
    total_stock_fin_value: "Total Stock Cost Value",
    potential_sale_value: "Potential Sale Value",
    total_stock_count: "Total Stock Quantity",
    category_financial_value: "Financial Value by Category",
    product_count: "Product Count",
    stock_qty: "Stock (qty)",
    financial_value: "Financial Value",
    category_stock_dist: "Stock Distribution by Category (kg)",
    product_stock_chart: "Product Stock Chart",
    daily_production_kg: "Daily Production (kg)",
    total_quantity_unit: "Total (qty)",
    total_quantity_kg: "Total (kg)",
    records: "Records",
    avg_qty: "Avg Qty",
    avg_kg: "Avg kg",
    total_exit_kg: "Total Exit (kg)",
    total_exit_qty: "Total Exit (qty)",
    exits_count: "Exit Count",
    daily_avg_kg: "Daily Avg (kg)",
    daily_exit_kg: "Daily Exit (kg)",
    customer: "Customer",
    exit_qty: "Exit (qty)",
    exit_kg: "Exit (kg)",
    product_based_exit: "Product-Based Exit",
    product: "Product",
    stock_by_category_header: "Total by Category (kg)",

    profile_info: "Profile Information",
    app_settings: "App Settings",
    user_management: "User Management",
    company_profile: "Company Profile",
    language: "Language",
    theme: "Theme",
    currency: "Currency",
    date_format: "Date Format",
    edit_profile: "Edit Profile",
    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    permission_count: "Permission Count",
    permissions: "Permissions",
    all_permissions: "All permissions",
    permission_dialog_desc: "Select which modules and actions this user can perform.",
    permission_save: "Save Permissions",
    settings_title: "Settings",
    company_profile_pdf_note: "Used on PDF receipts and reports",
    logo: "Logo",
    upload: "Upload",
    uploading: "Uploading...",
    logo_size_note: "JPG, PNG, WEBP, GIF • Max. 2 MB",
    company_name: "Company Name",
    website: "Website",
    save_company: "Save Company Info",
    toast_company_name_required: "Company name is required",
    toast_logo_too_big: "Logo must be at most 2 MB",
    toast_logo_type: "Only JPG, PNG, WEBP or GIF",
    toast_logo_updated: "Logo updated",
    toast_logo_removed: "Logo removed",
    toast_company_updated: "Company info updated",
    toast_updated: "Updated",
    toast_perms_updated: "Permissions updated",
    toast_user_deleted: "User deleted",
    toast_user_updated: "User updated",
    toast_profile_updated: "Profile updated",
    user_management_desc: "Edit each user's module-level permissions individually.",
    registered: "Registered",
    role_admin: "Administrator",
    role_personel: "Staff",
    role_rapor: "Report Only",
    permission_unit: "permission(s)",
    permission_management: "Permission Management",
    select_all: "Select All",
    deselect_all: "Deselect All",
    delete_user_q: "Delete user?",
    delete_user_desc: "will be deleted.",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "tr");

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => {
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.tr;
    return dict[key] ?? TRANSLATIONS.tr[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
